#!/usr/bin/expect -f

# connect via scp
spawn scp ./start-development-server.sh   docker@`boot2docker ip`:/home/docker/
#######################
expect {
  -re ".*es.*o.*" {
    exp_send "yes\r"
    exp_continue
  }
  -re ".*sword.*" {
    exp_send "tcuser\r"
  }
}
interact

